baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'ananke'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[[menu.main]]
  name = "Showcase"
  url = "/docs/showcase"
  weight = 30