name: Lint and Test

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '**'

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Check Nix Flake
        run: nix flake check

      - name: Install dependencies
        run: nix develop --command yarn install

      - name: Build all packages
        run: nix develop --command yarn build

      - name: Run linting
        run: nix develop --command yarn lint

      - name: Run tests
        run: nix develop --command yarn test

      - name: Install Playwright browsers
        run: nix develop --command npx playwright install --with-deps chromium

      - name: Run E2E tests
        run: nix develop --command yarn test:e2e:ci

      - name: Check formatting
        run: nix develop --command yarn format:check

      - name: Check types
        run: nix develop --command yarn typecheck
